In [1]:
# 2nd

import sklearn
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
train_text = ["A bird in hand is worth two in a bush.",
             "Good things come to those who grind.",
             "Those Airforces cost $120.",
             "There are other fishes in the sea.",
             "The ball is in your court.",
             "Mr. Lionel goes to Paris.",
             "Doogle Howser M.D."]

count_vectorizer = CountVectorizer()

In [3]:
count_vectorizer.fit(train_text)

CountVectorizer()

In [6]:
# gets all word tokens that count_vect has found
count_vectorizer.get_feature_names()

['120',
 'airforces',
 'are',
 'ball',
 'bird',
 'bush',
 'come',
 'cost',
 'court',
 'doogle',
 'fishes',
 'goes',
 'good',
 'grind',
 'hand',
 'howser',
 'in',
 'is',
 'lionel',
 'mr',
 'other',
 'paris',
 'sea',
 'the',
 'there',
 'things',
 'those',
 'to',
 'two',
 'who',
 'worth',
 'your']

In [7]:
# gives nothing since we didn't specify to remove stop words
count_vectorizer.get_stop_words()

In [8]:
# gets word found by count vect and int mapping(this is entire corpus to be used to transform new text)
count_vectorizer.vocabulary_

{'bird': 4,
 'in': 16,
 'hand': 14,
 'is': 17,
 'worth': 30,
 'two': 28,
 'bush': 5,
 'good': 12,
 'things': 25,
 'come': 6,
 'to': 27,
 'those': 26,
 'who': 29,
 'grind': 13,
 'airforces': 1,
 'cost': 7,
 '120': 0,
 'there': 24,
 'are': 2,
 'other': 20,
 'fishes': 10,
 'the': 23,
 'sea': 22,
 'ball': 3,
 'your': 31,
 'court': 8,
 'mr': 19,
 'lionel': 18,
 'goes': 11,
 'paris': 21,
 'doogle': 9,
 'howser': 15}

In [9]:
# get num id of just a wod
count_vectorizer.vocabulary_.get("mr")

19

In [16]:
# gets bag of words rep of the word encoding.
transformed_vector = count_vectorizer.transform(train_text)

In [17]:
print(transformed_vector.shape)  # rows number of sentences and col(33), vocab on which count vect was trained

(7, 32)


In [18]:
print(transformed_vector.toarray())

[[0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 2 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0]
 [1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [20]:
test_text = ["Every cloud has a silver lining."]

count_vectorizer.transform(test_text).toarray()  # since count vect hasn't seen it b4 feature vect is all zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [21]:
# train count vector with train and test text
count_vectorizer.fit(train_text + test_text)

CountVectorizer()

In [22]:
print(count_vectorizer.vocabulary_)

{'bird': 4, 'in': 19, 'hand': 16, 'is': 20, 'worth': 35, 'two': 33, 'bush': 5, 'good': 14, 'things': 30, 'come': 7, 'to': 32, 'those': 31, 'who': 34, 'grind': 15, 'airforces': 1, 'cost': 8, '120': 0, 'there': 29, 'are': 2, 'other': 24, 'fishes': 12, 'the': 28, 'sea': 26, 'ball': 3, 'your': 36, 'court': 9, 'mr': 23, 'lionel': 22, 'goes': 13, 'paris': 25, 'doogle': 10, 'howser': 18, 'every': 11, 'cloud': 6, 'has': 17, 'silver': 27, 'lining': 21}


In [23]:
count_vectorizer.transform(test_text).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [25]:
# contains some words known to count vect and some that are unknown
text = ["That bird is sitting in the bush and this bird is in hand.",
       "Wait and then walk",
       "Watches are cool"]

transformed_vector = count_vectorizer.transform(text)

transformed_vector # sparse mat means matrix contains entries for only words present in particular sentence

<3x37 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [26]:
# first col in tuple is sentence, second col in tuple is id of word
# last col is for the frequency of the word

print(transformed_vector)

  (0, 4)	2
  (0, 5)	1
  (0, 16)	1
  (0, 19)	2
  (0, 20)	2
  (0, 28)	1
  (2, 2)	1


In [27]:
# using bag of words to rep text stored in file
with open("./datasets/biography.txt", "r") as file:
    file_contents = file.read()
    
print(file_contents)

Marie Skłodowska Curie  born Maria Salomea Skłodowska , was a Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. As the first of the Curie family legacy of five Nobel Prizes, she was the first woman to win a Nobel Prize, the first person and the only woman to win the Nobel Prize twice, and the only person to win the Nobel Prize in two scientific fields. She was the first woman to become a professor at the University of Paris in 1906.[4]

She was born in Warsaw, in what was then the Kingdom of Poland, part of the Russian Empire. She studied at Warsaw's clandestine Flying University and began her practical scientific training in Warsaw. In 1891, aged 24, she followed her elder sister Bronisława to study in Paris, where she earned her higher degrees and conducted her subsequent scientific work. In 1895 she married the French physicist Pierre Curie, and she shared the 1903 Nobel Prize in Physics with him and with the physicist Henri B

In [28]:
# splits text into sentences for easy use with countVect, could have used sentences tokenizer
# especially in real world projects
sentences = file_contents.split("\n")

print(sentences)

['Marie Skłodowska Curie  born Maria Salomea Skłodowska , was a Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. As the first of the Curie family legacy of five Nobel Prizes, she was the first woman to win a Nobel Prize, the first person and the only woman to win the Nobel Prize twice, and the only person to win the Nobel Prize in two scientific fields. She was the first woman to become a professor at the University of Paris in 1906.[4]', '', 'She was born in Warsaw, in what was then the Kingdom of Poland, part of the Russian Empire. She studied at Warsaw\'s clandestine Flying University and began her practical scientific training in Warsaw. In 1891, aged 24, she followed her elder sister Bronisława to study in Paris, where she earned her higher degrees and conducted her subsequent scientific work. In 1895 she married the French physicist Pierre Curie, and she shared the 1903 Nobel Prize in Physics with him and with the physicis

In [29]:
transformed_vector = count_vectorizer.fit_transform(sentences)

transformed_vector.shape

(7, 202)

In [30]:
print(transformed_vector)

  (0, 100)	1
  (0, 156)	2
  (0, 112)	2
  (0, 45)	2
  (0, 31)	1
  (0, 99)	1
  (0, 146)	1
  (0, 188)	3
  (0, 128)	1
  (0, 20)	4
  (0, 107)	1
  (0, 73)	1
  (0, 123)	1
  (0, 37)	1
  (0, 193)	1
  (0, 42)	1
  (0, 126)	1
  (0, 144)	1
  (0, 114)	1
  (0, 137)	1
  (0, 22)	1
  (0, 167)	10
  (0, 66)	4
  (0, 113)	3
  (0, 63)	1
  :	:
  (6, 75)	1
  (6, 142)	1
  (6, 111)	2
  (6, 116)	1
  (6, 81)	1
  (6, 176)	1
  (6, 10)	1
  (6, 26)	1
  (6, 25)	1
  (6, 61)	1
  (6, 117)	1
  (6, 103)	1
  (6, 118)	1
  (6, 1)	1
  (6, 47)	1
  (6, 11)	1
  (6, 201)	2
  (6, 86)	1
  (6, 89)	2
  (6, 161)	1
  (6, 30)	1
  (6, 199)	1
  (6, 18)	1
  (6, 93)	1
  (6, 97)	1


In [31]:
print(count_vectorizer.vocabulary_)

{'marie': 100, 'skå': 156, 'odowska': 112, 'curie': 45, 'born': 31, 'maria': 99, 'salomea': 146, 'was': 188, 'polish': 128, 'and': 20, 'naturalized': 107, 'french': 73, 'physicist': 123, 'chemist': 37, 'who': 193, 'conducted': 42, 'pioneering': 126, 'research': 144, 'on': 114, 'radioactivity': 137, 'as': 22, 'the': 167, 'first': 66, 'of': 113, 'family': 63, 'legacy': 95, 'five': 67, 'nobel': 110, 'prizes': 132, 'she': 154, 'woman': 196, 'to': 172, 'win': 194, 'prize': 131, 'person': 122, 'only': 115, 'twice': 177, 'in': 84, 'two': 178, 'scientific': 150, 'fields': 65, 'become': 27, 'professor': 133, 'at': 23, 'university': 181, 'paris': 119, '1906': 5, 'warsaw': 187, 'what': 190, 'then': 170, 'kingdom': 92, 'poland': 127, 'part': 120, 'russian': 145, 'empire': 60, 'studied': 158, 'clandestine': 40, 'flying': 68, 'began': 29, 'her': 78, 'practical': 130, 'training': 174, '1891': 2, 'aged': 17, '24': 12, 'followed': 69, 'elder': 57, 'sister': 155, 'broniså': 33, 'awa': 24, 'study': 160, 

In [32]:
# tries to ret original sentecnes from it's word count
count_vectorizer.inverse_transform(transformed_vector)

[array(['marie', 'skå', 'odowska', 'curie', 'born', 'maria', 'salomea',
        'was', 'polish', 'and', 'naturalized', 'french', 'physicist',
        'chemist', 'who', 'conducted', 'pioneering', 'research', 'on',
        'radioactivity', 'as', 'the', 'first', 'of', 'family', 'legacy',
        'five', 'nobel', 'prizes', 'she', 'woman', 'to', 'win', 'prize',
        'person', 'only', 'twice', 'in', 'two', 'scientific', 'fields',
        'become', 'professor', 'at', 'university', 'paris', '1906'],
       dtype='<U13'),
 array([], dtype='<U13'),
 array(['marie', 'curie', 'born', 'was', 'and', 'french', 'physicist',
        'conducted', 'pioneering', 'radioactivity', 'the', 'of', 'nobel',
        'she', 'to', 'prize', 'in', 'scientific', 'at', 'university',
        'paris', '1906', 'warsaw', 'what', 'then', 'kingdom', 'poland',
        'part', 'russian', 'empire', 'studied', 'clandestine', 'flying',
        'began', 'her', 'practical', 'training', '1891', 'aged', '24',
        'followed', '